version: '3.0'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    build: prometheus
    image: priorartarchive/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090